# Generated by Django 6.0.2 on 2026-02-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_alive', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
