# Generated by Django 6.0.2 on 2026-02-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('town', 'Town'), ('mafia', 'Mafia'), ('neutral', 'Neutral')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
