# Generated by Django 6.0.2 on 2026-02-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='virtue',
            field=models.SmallIntegerField(default=0),
        ),
    ]
