# Generated by Django 6.0.2 on 2026-02-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('night', 'Night'), ('discussion', 'Discussion'), ('defense', 'Defense'), ('voting', 'Voting')], default='discussion', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_games', to='game.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_night_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='night_priority',
            field=models.IntegerField(blank=True, help_text='Lower number acts earlier at night', null=True),
        ),
    ]
