# Generated by Django 6.0.2 on 2026-02-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_current_phase_game_current_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='night_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='no_first_night',
            field=models.BooleanField(default=False),
        ),
    ]
