# Generated by Django 6.0.2 on 2026-02-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_night_number_role_no_first_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_phase',
            field=models.CharField(max_length=10),
        ),
    ]
