# Generated by Django 6.0.2 on 2026-02-15 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_current_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.role'),
        ),
    ]
