# Generated by Django 6.0.2 on 2026-02-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_current_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='blackmailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='cursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='executionerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='on_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='protection_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.role'),
        ),
    ]
