# Generated by Django 6.0.2 on 2026-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_attacked_player_blackmailed_player_cleaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='mafia_priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
