# Generated by Django 6.0.2 on 2026-02-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_role_mafia_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_game_role',
            field=models.BooleanField(default=True),
        ),
    ]
