# Generated by Django 6.0.2 on 2026-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_role_is_game_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
